### ISSUE TITLE
[DOCS] Add quasar and @quasar/extras dependencies reminder

### ISSUE THREAD

**Issue by angelhdzmultimedia** [Maiquu/nuxt-quasar#1]
Excelent module! Appreciate your time and effort. We are very close to having Quasar + Nuxt + SSR!

It would be nice to add in the docs a reminder to install `quasar `and `@quasar/extras` packages.

 Some people may be misdirected into thinking that this nuxt module also installs the dependencies.
 
 I personally imagined I would have to install them and I did, and didn't have issues, but then decided to test, and uninstalled them, and bam error, and I was like "I knew it!" haha.
 
 My only issue was not adding the fonts in nuxt.config.ts under the quasar object so for example the up and down arrows of a QSelect wouldn't show.
 
 Wishing you health and success!

**Comment by Maiquu** [comment]
Hello! Thanks a lot for the feedback!

Hopefully this PR (#2) will eliminate the confusion regarding peer dependencies and missing icons on components.

Cheers!
