### ISSUE TITLE
[BUG] - Doesn't work with Nuxt content module

### ISSUE THREAD

**Issue by Seanitzel** [Maiquu/nuxt-quasar#10]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Nuxt-Quasar version

1.0.5

### Browsers

Other

### Description

I'm trying to migrate to this module from [The Nuxt-Quasar](https://github.com/memotux/nuxt-quasar) module, however it looks like it doesn't work with nuxt content.

When adding the content module in the nuxt config the following error pops up(which prevents building the project, but still allows local development)

` ERROR  Failed to resolve import "@quasar/quasar-app-extension-testing-e2e-cypress" from "node_modules/quasar/src/components/select/__tests__/QSelect.cy.js?v=58bc2a45". Does the file exist?
`
![image](https://user-images.githubusercontent.com/16267397/226349041-66669ca4-bf05-46fd-9374-dbf8467e2df4.png)

Btw i wasn't sure whether i should open this as a bug or feature request, so if needed ill change it :)
Also Thanks for creating this awesome module :)

### Reproduction

https://stackblitz.com/edit/github-g9bzsz-dxbyzb?file=nuxt.config.ts

I basically just installed the content module, and added it to nuxt.config.

**Comment by Maiquu** [comment]
Hello, glad you liked it.

This issue is pretty weird... For some reason adding `@nuxt/content`, causes quasar test files to be included in build. I'll be looking into it.

**Comment by Maiquu** [comment]
Ok figured it out. It's not related to `@nuxt/content` at all. It's an issue with the newest `quasar` version. They added test components to `import-map.json` file, which module uses to add components for auto-import. Will release a new version shortly.

**Comment by Seanitzel** [comment]
Haha yea what a weird issue, i also couldn't think of a reason it would be related to nuxt/content but it stopped occuring when i removed it from the modules array 🤣 

nice addition to the issue template, and thanks for being so nice and fast :)
