### ISSUE TITLE
[BUG] - sass @import deprecation warning

### ISSUE THREAD

**Issue by summitmarkcasiano** [Maiquu/nuxt-quasar#103]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

Nuxt project info:      

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  nuxt-quasar-ui@2.1.6
- Build Modules:    -
------------------------------

### Quasar version

2.1.6

### Browsers

Google Chrome

### Description

These deprecation warnings cannot be suppressed when using the `sassVariable` field.

### Reproduction steps

```bash
1. Go to https://stackblitz.com/edit/nuxt-starter-nbbpne?file=pages%2Findex.vue,package.json
2. check console
```

**Comment by Maiquu** [comment]
`sass@1.80.0` deprecated a lot of things that quasar uses in its `sass` code. I suggest staying below `sass@1.80.0` but if you want, you can suppress deprecation warnings like this:

```ts
// nuxt.config.ts
export default defineNuxtConfig({
  // ...
  vite: {
    css: {
      preprocessorOptions: {
        sass: {
          silenceDeprecations: ['import', 'global-builtin', 'legacy-js-api'],
        }
      },
    },
  },
  // ...
})
```

**Comment by adamkpurdy** [comment]
@Maiquu Thank you for this.

**Comment by summitmarkcasiano** [comment]
@Maiquu thank you.
