### ISSUE TITLE
[BUG] - Empty type declaration file for plugin.js

### ISSUE THREAD

**Issue by AapoPitkanen** [Maiquu/nuxt-quasar#104]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.17.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      default
- Runtime Modules:  nuxt-quasar-ui@2.1.6
- Build Modules:    -
------------------------------

### Quasar version

2.17.2

### Browsers

Google Chrome

### Description

Currently the type declaration file plugin.d.ts in nuxt-quasar-ui/dist/runtime/plugin.d.ts file is empty, causing TypeScript to evaluate the type of NuxtAppInjections as any, as seen in the generated plugin.d.ts file in .nuxt/types/plugin.d.ts. The incorrect typing also breaks other plugins that might be added to the project, such as the example plugin provided in the Nuxt documentation:

```
export default defineNuxtPlugin(() => {
  return {
    provide: {
      hello: (msg: string) => `Hello ${msg}!`
    }
  }
})
```

This causes incorrect typing when trying to use plugins with useNuxtApp(). For example, trying to call the example plugin app.$hello will cause the TypeScript error 'app.$hello' is of type 'unknown'. Commenting out the InjectionType<typeof import("../../node_modules/nuxt-quasar-ui/dist/runtime/plugin.js")> line in .nuxt/types/plugin.d.ts restores correct typing. 

I fixed the issue locally by manually adding this to the nuxt-quasar-ui/dist/runtime/plugin.d.ts file:

```
import { QuasarPluginOptions, QVueGlobals } from 'quasar';

declare module '#app' {
  interface NuxtApp {
    $q: QuasarPluginOptions;
  }
}

declare module 'vue' {
  interface ComponentCustomProperties {
    $q: QVueGlobals;
  }
}

```
Although I'm unsure what the actual correct plugin type should be for the Quasar plugin.

Incorrect typing:
<img width="427" alt="incorrect-types" src="https://github.com/user-attachments/assets/0b31700d-2ec0-4e56-8081-c74350ef6242">

Correct typing:
<img width="428" alt="correct-types" src="https://github.com/user-attachments/assets/d44a388b-a974-4f5d-916f-d81b9ef51ec8">

### Reproduction steps

```bash
1. Create a new Nuxt project by running npx nuxi init my-new-nuxt-project
2. Install nuxt-quasar ui by running npx nuxi module add nuxt-quasar-ui
3. Inspect the generated plugin.d.ts file in .nuxt/types/plugin.d.ts
4. Verify that the type of NuxtAppInjections evaluated as any
5. Comment out the line InjectionType<typeof import("../../node_modules/nuxt-quasar-ui/dist/runtime/plugin.js")>
6. Verify the type of NuxtAppInjections evaluated correctly
```

**Comment by Maiquu** [comment]
Thanks, I should pay more attention to CI warnings.
