### ISSUE TITLE
[BUG] - Screen plugin doesn't work

### ISSUE THREAD

**Issue by Seanitzel** [Maiquu/nuxt-quasar#11]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Nuxt-Quasar version

1.0.5

### Browsers

Chromium

### Description

The Quasar screen plugin doesn't work as expected for some reason.
It exists on the Quasar instance, but it doesn't recognise the environment correctly and e.g says the width and height are 0.

![image](https://user-images.githubusercontent.com/16267397/226354498-dde8db08-e88f-447d-8c72-927690971de6.png)

### Reproduction

https://stackblitz.com/edit/github-g9bzsz-tfpszv?file=pages/index.vue

**Comment by Maiquu** [comment]
Release new version, should fix the issue with Dark and Screen plugins.

**Comment by Seanitzel** [comment]
Thanks for fixing it so quickly!! 😄

**Comment by Maiquu** [comment]
@sebaguse Could not reproduce the issue, can you provide a reproduction?

**Comment by sebaguse** [comment]
Hi @Maiquu, I think my issue might be the result of misunderstanding how Screen plugin supposed to work with SSR, but I found this issue [https://github.com/quasarframework/quasar/issues/5079](https://github.com/quasarframework/quasar/issues/5079) which explained the topic a little bit more. Thanks and sorry for wasting your time!
