### ISSUE TITLE
[BUG] - Style overriding not working in dev-server environment.

### ISSUE THREAD

**Issue by Saeid-Za** [Maiquu/nuxt-quasar#15]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.29.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Quasar version

2.11.7

### Browsers

Microsoft Edge

### Description

I'm using a custom.scss file to override quasar styles.
While working on nuxt development mode, server sends the following `head` content.

![dev-server](https://user-images.githubusercontent.com/65568529/226746548-0173ba1d-7a19-4970-ac1f-766edf3a24dd.png)

There are two problems with this `head` content:

1. there are duplicate css links for any quasar related imports, one starting with `/_nuxt/<path-to-file>` and the other with `/nuxt/@fs/<path-fo-file>`. any quasar related path that starts with the first mode, resolves to 404 (nuxt reports that file does not exist).
2. Although nuxt doesn't seem to find the reported file, user land style (`custom.scss` in this case) gets overridden, meaning that quasar.css file is imported after `custom.scss`.

After hydration and meta tag changes, `head` tag fixes itself:

![dev-client](https://user-images.githubusercontent.com/65568529/226747901-9e25d68d-f089-4527-9055-14df35d09d9e.png)

I'd also tested this scenario in production mode. this problem doesn't exist on that mode.
`head` content Before & after hydration is the same.

![build](https://user-images.githubusercontent.com/65568529/226748214-68c32148-55d5-41a0-86c2-53edadefaf55.png)

### Reproduction steps

```
1. Clone `Maiquu/nuxt-quasar` repo.
2. Add a `custom.scss` file to `assets` folder and then include it in `nuxt.config` css array.
2. Run playground in development mode.
3. Check `head` content of response from server and then compare it with client html after hydraion (via browser inspecting)
4. custom.scss importing order is not the same.
```

**Comment by Maiquu** [comment]
I followed all the reproduction steps. The content server sends is indeed as you described. But I think this is how nuxt works behind the scenes. It did not show any errors or warning related to hydration.

As for the main issue regarding not being able to override `quasar.css`, I didn't had any problems. I created almost the same environment you provided me. (Except I had node v18.15.0) I tried it on StackBlitz demo but no issues there either.

Can you create a StackBlitz fork of the demo and try to reproduce, I might be missing something.

**Comment by Saeid-Za** [comment]
I can't reproduce this in 1.3.0, this issue can be closed.
Thanks for the new release.
