### ISSUE TITLE
💡 [REQUEST] - Persistent Dark mode

### ISSUE THREAD

**Issue by Saeid-Za** [Maiquu/nuxt-quasar#16]
### Describe the feature

First of all, thanks for this great nuxt-module.
As the title suggests, `nuxt-quasar` could add utilities to support cookie-based dark mode. in this scenario, dark mode settings would be saved on client's browser and server would render html based on user's preference.
I've added a simple implementation to my own projects, and i'll be glad to help contributing this feature if approved.

One concern would be that, implementing this feature would segregate this repository from being a nuxt-quasar module only as it would be a feature that quasar doesn't support currently.
The same idea could be applied on supporting quasar `locales` and direction (LTR/RTL)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by JasonLandbridge** [comment]
Interesting idea! Maybe we could move towards splitting up this repository:

1. **nuxt-quasar** - The barebones Quasar plugin for Nuxt
2. **nuxt-quasar-extras** - Same system as how Quasar does it, where optional features can be enabled such as cookie-based dark mode
3. **nuxt-quasar-playground** - The example playground project with various configurations where features or bugs could be showcased and reproduced

@Maiquu, what do you think?

**Comment by Maiquu** [comment]
Persistent Dark mode should be possible with next patch. You should be able to achieve it with via nuxt's own [`useCookie`](https://nuxt.com/docs/api/composables/use-cookie) method.
