### ISSUE TITLE
💡 [REQUEST] - Add a property to set default language pack in the Nuxt config.

### ISSUE THREAD

**Issue by Hime-Hina** [Maiquu/nuxt-quasar#31]
### Describe the feature

Hello!

I think it would be useful to configure default language pack in the Nuxt config file.
Just like:

```js
export default defineNuxtConfig({
  // ...
  quasar: {
    lang: 'zh-CN',
    // ...
  }
}
```

I'm not sure whether it is enough to add some code to `plugin.ts` and `module.ts`.

EDIT: I have not noticed that there is a feature branch implementing this😂. It seems sufficient for me. When will it be released?

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by Maiquu** [comment]
Feel free to send a PR. It's similar to how `iconSet` is set at `plugin.ts` file.
