### ISSUE TITLE
💡 [REQUEST] - Setting the default Quasar component prop values

### ISSUE THREAD

**Issue by JasonLandbridge** [Maiquu/nuxt-quasar#35]
### Describe the feature

Hi there, 

First of all, amazing work @Maiquu! I keep watching you make awesome updates, huge thank you for that!

I found a way to set the default prop values for Quasar components without creating wrapper components. It might be an interesting idea to make this part of Nuxt-Quasar as well. 

Source: https://github.com/quasarframework/quasar/discussions/8761#discussioncomment-1042529

It's a bit of a long thread but the end result, that works with Nuxt-Quasar, is the following:

```ts
// Source: https://github.com/quasarframework/quasar/discussions/8761#discussioncomment-1042529
// This part could be exported from Nuxt-Quasar
type ExtractComponentProps<T> = T extends ComponentConstructor<infer X> ? X['$props'] : never;
export const setQuasarComponentDefaultPropValues = <T extends ComponentConstructor>(
 component: T,
 propDefaults: {
  [K in keyof Partial<ExtractComponentProps<T>>]: ExtractComponentProps<T>[K];
 },
) => {
 for (const key in propDefaults) {
  const prop = component.props[key];
  switch (typeof prop) {
   case 'object':
    prop.default = propDefaults[key];
    break;
   case 'function':
    component.props[key] = {
     type: prop,
     default: propDefaults[key],
    };
    break;
   case 'undefined':
    throw new Error('unknown prop: ' + key);
   default:
    throw new Error('unhandled type: ' + typeof prop);
  }
 }
};
```

Then the user can create a simple [Nuxt plugin](https://nuxt.com/docs/guide/directory-structure/plugins) like this:

```ts
// [root]/plugins/quasar-defaults.ts
import { defineNuxtPlugin } from '#app';
import { setQuasarComponentDefaultPropValues } from 'nuxt-quasar'
import {
 ComponentConstructor,
 QCircularProgress,
 QLinearProgress,
 QSelect,
 QToggle,
 QExpansionItem,
 QMarkupTable,
 QTable,
 QInput,
} from 'quasar';

export default defineNuxtPlugin(() => {
 setQuasarComponentDefaultPropValues(QInput, {
  outlined: true,
 });

 setQuasarComponentDefaultPropValues(QSelect, {
  outlined: true,
  dense: true,
  dropdownIcon: 'mdi-chevron-down',
  clearIcon: 'mdi-close',
 });

 setQuasarComponentDefaultPropValues(QToggle, {
  color: 'red',
  checkedIcon: 'mdi-check',
  uncheckedIcon: 'mdi-close',
 });

 setQuasarComponentDefaultPropValues(QMarkupTable, {
  flat: true,
 });

 setQuasarComponentDefaultPropValues(QTable, {
  color: 'red',
 });

 setQuasarComponentDefaultPropValues(QExpansionItem, {
  expandIcon: 'mdi-chevron-down',
  expandedIcon: 'mdi-chevron-up',
 });

 setQuasarComponentDefaultPropValues(QCircularProgress, {
  color: 'red',
  indeterminate: true,
 });

 setQuasarComponentDefaultPropValues(QLinearProgress, {
  color: 'red',
  stripe: true,
 });
});

```

- The above works perfectly and ensures a lot less passing in of props to components where the default value should always be the same.
- I would only change the name of `setQuasarComponentDefaultPropValues` to something shorter like `SetDefaultPropValues` or something. 
- At least in Webstorm, all options are auto-completed and type safe so only valid props with valid values can be defined. 
- All values set are over-writable when the component is used and a different prop value is passed in

Would you like this to be part of Nuxt-Quasar?

Cheers!

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by Maiquu** [comment]
This is amazing.  We can indeed make it a part of the module as a composable. I find it odd why this functionality is not part of the Quasar.

> I would only change the name of setQuasarComponentDefaultPropValues to something shorter like SetDefaultPropValues or something.

I agree. It's a bit too explicit.

You are welcome to make a PR for this. I can also work on it a later date.

**Comment by JasonLandbridge** [comment]
Awesome, I'm only concerned where to place everything such that it fits your code organization. 

Can I just make this function part of Module.ts and export it from there?

And yes I can make it tomorrow!

**Comment by Maiquu** [comment]
Nuxt requires modules to include runtime code (like components, composables) under `src/runtime` directory. So you can export it from a fresh file under that directory. [Reference](https://nuxt.com/docs/guide/going-further/modules#runtime-directory)

Then it should be included via `addImport` at `module.ts`.

Thanks

**Comment by JasonLandbridge** [comment]
Thanks for the tips! Working on it now

**Comment by Maiquu** [comment]
I have an idea on this, I will test it out tomorrow

**Comment by Maiquu** [comment]
I implemented my idea on component defaults at branch [feat/prop-defaults](https://github.com/Maiquu/nuxt-quasar/tree/feat/prop-defaults). Would really appreciate it if you could give feedback on it @JasonLandbridge.

**Comment by JasonLandbridge** [comment]
Looks impressive! Could you make a PR so I can provide better feedback/questions?

**Comment by Maiquu** [comment]
Sure. #39

**Comment by JasonLandbridge** [comment]
@Maiquu , I think this issue can be closed for now and it can maybe be considered again in the future
