### ISSUE TITLE
💡 [REQUEST] - include cssAddon

### ISSUE THREAD

**Issue by artnova-david** [Maiquu/nuxt-quasar#41]
### Describe the feature

Hi,
Is it or would it be possible to include cssAddon (https://quasar.dev/layout/grid/introduction-to-flexbox#flex-addons) in the nuxt-quasar configuration?

Thanks in advance
Kind regards

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by Maiquu** [comment]
Closed by #44. Will be included in next minor release.
