### ISSUE TITLE
This plugin is awesome!

### ISSUE THREAD

**Issue by JasonLandbridge** [Maiquu/nuxt-quasar#5]
Hi there!

Huge thank you for making this! I'm currently migrating from Vuetify to Quasar and I haven't come accross any issues so well done!

Would you consider adding a reference to this module on the [Nuxt/Modules](https://github.com/nuxt/modules) repo? That way it will show up on the [nuxt modules directory](https://nuxt.com/modules?q=quasar) page and more people can find it. 

Cheers!

**Comment by Maiquu** [comment]
Hello, thanks for your feedback! :+1:

I already considered adding reference to `nuxt/modules` repo. I just sent a pull request to it. You can track the PR [here](https://github.com/nuxt/modules/pull/602). I will close the issue when its merged.
