### ISSUE TITLE
💡 [REQUEST] - rtl support

### ISSUE THREAD

**Issue by mozhgan-k** [Maiquu/nuxt-quasar#54]
### Describe the feature

Hi,
Thanks for this great Nuxt module.
Could you please add rtl support for this?
Thank you in advance !

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by JasonLandbridge** [comment]
Follow this guide: https://quasar.dev/options/rtl-support/

If you can't make it work, then be specific in what you need that isn't already in nuxt-quasar

**Comment by mozhgan-k** [comment]
I read the documentation.
The HTML tag has `dir="rtl"` and `lang="fa-IR"` but in `quasar.css` html and body dir is LTR.
my nuxt.config.ts is:
`export default defineNuxtConfig({
  modules: ['nuxt-quasar-ui'],
  quasar: {
    extras: {},
    lang: 'fa-IR',
    build: {
      rtl: true
    }
  }
})`,

and postcss.config.cjs :
`module.exports = {
  plugins: [
    require('postcss-rtlcss')({ source: 'rtl'  }) 
  ]
}`
nuxt version : "^3.5.2" and  postcss-rtlcss: "^4.0.6"

and my app is still LTR

**Comment by Maiquu** [comment]
Try following `nuxt.config.ts`
```ts
export default defineNuxtConfig({
  app: {
    head: {
      htmlAttrs: {
        dir: 'rtl',
      },
    },
  },
  modules: ['nuxt-quasar-ui'],
  postcss: {
    plugins: {
      'postcss-rtlcss': {},
    },
  },
  quasar: {
    lang: 'fa-IR',
  }
}
```

**Comment by mozhgan-k** [comment]
fixed! thank you
