### ISSUE TITLE
[BUG] - Cannot use svg icons.

### ISSUE THREAD

**Issue by DanielIvashev** [Maiquu/nuxt-quasar#55]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.17.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@8.19.3
- Builder:          vite
- User Config:      modules, i18n, quasar, css, components, vite
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-beta.12, nuxt-quasar-ui@1.7.4
- Build Modules:    -
------------------------------

### Quasar version

v2.12.0

### Browsers

Google Chrome

### Description

Hi! First of all I want to say that you have done a great job, thank you.
Faced with the problem of using svg icons.

I see that there is no way to take the icons directly into quasar. Only through @quasar/extras. Although quasar itself provides for importing svg icons.

![image](https://github.com/Maiquu/nuxt-quasar/assets/62364141/4f3289f5-669c-4596-b3a8-8558f329bff1)
![image](https://github.com/Maiquu/nuxt-quasar/assets/62364141/3f40a8d7-7f2e-420b-a316-e15b59d83f5c)

### Reproduction steps

```bash
Just try to import svg icons
```

**Comment by Maiquu** [comment]
Closed by #57 ([3503262](https://github.com/Maiquu/nuxt-quasar/commit/3503262), [5d5109b](https://github.com/Maiquu/nuxt-quasar/commit/5d5109b))
