### ISSUE TITLE
[BUG] - Quasar icons show as text

### ISSUE THREAD

**Issue by paulofbr** [Maiquu/nuxt-quasar#58]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

- Operating System: Windows_NT
- Node Version:     v20.2.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@2.15.12
- Builder:          vite
- User Config:      modules, quasar, devtools, typescript, css
- Runtime Modules:  nuxt-quasar-ui
- Build Modules:    -

### Quasar version

2.12

### Browsers

Google Chrome

### Description

Quasar icons appear as text, as shown in the image below

![image](https://github.com/Maiquu/nuxt-quasar/assets/3792868/d02c576d-d4a6-4ccc-9885-452664e0ca4e)

![image](https://github.com/Maiquu/nuxt-quasar/assets/3792868/75a5d9e5-857b-42a2-b464-3d6918119588)

### Reproduction steps

```bash
1. add icon to a page 
2. npm run dev
```

### Screenshots

```bash
![image](https://github.com/Maiquu/nuxt-quasar/assets/3792868/d02c576d-d4a6-4ccc-9885-452664e0ca4e)
```

**Comment by Maiquu** [comment]
You need to install/include font icons of your choosing for icons used by quasar components as described [here](https://github.com/Maiquu/nuxt-quasar/tree/v1.7.4#regarding-component-icons). 

In next major release, this will be automatically (with option to opt-out to current behaviour).
