### ISSUE TITLE
💡 [REQUEST] - Fix an issue with the Demo 

### ISSUE THREAD

**Issue by Seanitzel** [Maiquu/nuxt-quasar#62]
### Describe the feature

Hi there!

The [Demo](https://stackblitz.com/edit/github-g9bzsz?file=layouts%2Fdefault.vue) in stack blitz has an issue that can confuse and mislead people on how to use quasar with nuxt(or nuxt in general).

The demo at the moment is built like so:

app.vue
```Vue
<template>
  <NuxtLayout />
</template>
```

layouts/default.vue
```Vue
<template>
  <q-layout view="lHh Lpr lFf">
  ....
    <q-page-container>
      <NuxtPage />
    </q-page-container>
  </q-layout>
</template>
```

pages/index.vue
```Vue
<template>
<q-page class="q-pl-lg">
   ...
</q-page>
</template>
  ```
  
  This is not how it should be and actually prevents from using different layouts.
  
  The correct way to do it(according to Nuxt docs) is:
  
  app.vue
```Vue
<template>
  <NuxtPage />
</template>
```

layouts/default.vue
```Vue
<template>
  <q-layout view="lHh Lpr lFf">
  ....
    <q-page-container>
      <slot />
    </q-page-container>
  </q-layout>
</template>
```

pages/index.vue
```Vue
<template>
  <div>
    <NuxtLayout>
      <q-page class="q-pl-lg">
     ...
      </q-page>
    </NuxtLayout>
  </div>
</template>
  ```
  
  This gives the flexibility to use different layouts with pages by using 
  `<NuxtLayout name="other-layout">`

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by Maiquu** [comment]
Thanks. I made it similar to documentation example [here](https://nuxt.com/docs/guide/directory-structure/layouts#setting-another-layout) instead of using `<NuxtLayout>` directly in pages.

**Comment by Seanitzel** [comment]
Ohh i actually missed that, sorry!
