### ISSUE TITLE
💡 [REQUEST] - Routes intellisense/completion

### ISSUE THREAD

**Issue by angelhdzmultimedia** [Maiquu/nuxt-quasar#64]
### Describe the feature

Hi mate!

This time I'm gonna propose a feature request.

I just learned Nuxt has the experimental flag `typedRouter` to have completion of the routes everywhere we need it like in `navigateTo()`.

It works beautifully!

Now, of course, Quasar components `to` attribute does not have route completion,
so I was wondering if you are up to add this functionality.

Apparently Nuxt is using the `unplugin-vue-router` package, from the creator of `vue-router`, so there should be a types file generated somewhere we could leverage to get the routes list.

To me, the challenging part would be to override the components to define a new `to` attribute with an union of the routes as type, and using the new `<script generic="T">` attribute to have completion in the template.

Or maybe we don't need to override the components at all, and just define a virtual types file of the new structure of the components.

I propose this here because the creator of Quasar seems not interested in contributing to the Nuxt community (the fact that you had to create this module in the first place confirms it).

I already achieved it by creating a proxy for the `QBtn` for example:

![image](https://github.com/Maiquu/nuxt-quasar/assets/10191085/46ecb8ae-e93d-4ab9-b725-adc27bf6529b)

![image](https://github.com/Maiquu/nuxt-quasar/assets/10191085/9942a1a3-e021-4d31-8377-9515c9d8dd3e)

It would be nice! 

Wishing you the health. Have a nice day.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by angelhdzmultimedia** [comment]
After discussing this with someone in Quasar's Discord, 
I solved this by using custom Quasar components which I can then type appropriately, 
and also, thanks to Nuxt great TypeScript support, I could extract the routes paths from the first parameter of the `navigateTo` hook!


https://github.com/Maiquu/nuxt-quasar/assets/10191085/d8240677-32de-421c-84fc-2907945acf3b



Hope this helps someone. :)

**Comment by Maiquu** [comment]
Nice! Maybe it could also be possible via module augmentation. I'll probably try tomorrow.

**Comment by angelhdzmultimedia** [comment]
### Update

Nuxt implements `vue-router/auto`, so I found the routes type and extracted the paths from it.

![image](https://github.com/Maiquu/nuxt-quasar/assets/10191085/b551459b-daa7-473c-b0e3-30ca6dad0704)

**Comment by Maiquu** [comment]
Sadly this may not be possible via module augmentation due to `quasar`'s own types marking `to` props as `any` which eliminates auto-completion entirely. Another solution would be to re-create the quasar types in module level or a PR to `quasar` repository to enhance component types (or the process of generating them during build-time).

**Comment by angelhdzmultimedia** [comment]
### Update

One of Quasar's team members, after my suggestion, added this! https://github.com/quasarframework/quasar/pull/16088
