### ISSUE TITLE
[BUG] - [sass] Undefined variable

### ISSUE THREAD

**Issue by sebaguse** [Maiquu/nuxt-quasar#65]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      app, runtimeConfig, css, modules, quasar, pinia, imports, vite, devtools, content
- Runtime Modules:  nuxt-quasar-ui@2.0.2, @pinia/nuxt@0.4.11, @vueuse/nuxt@10.2.1, @pinia-plugin-persistedstate/nuxt@1.1.1, @nuxt/content@2.7.0
- Build Modules:    -
------------------------------

### Quasar version

v2.12.1

### Browsers

Google Chrome

### Description

Thank you for this amazing module! I have a small issue with it, for some reason I can't use Quasar's predefined color variables, I get an error:

```bash
 ERROR  [sass] Undefined variable.                                                                                                                                                       12:27:22  
   ╷
24 │     color: $grey-1;
   │            ^^^^^^^
   ╵
  layouts\default.vue 24:12  root stylesheet
```

My code (scoped SCSS):
```css
  .my-menu-link {
    color: $grey-1;
    background: $grey-8;
  }
```

### Reproduction steps

```bash
1. Add scoped SCSS to your code
2. Use Quasar's color variable in your SCSS code
3. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by angelhdzmultimedia** [comment]
Did you install `sass@1.12.32`?

![image](https://github.com/Maiquu/nuxt-quasar/assets/10191085/a8f921b8-336b-4221-95a0-beb91f86c8fa)

**Comment by Maiquu** [comment]
You may need to set `sassVariables` to `true` in `nuxt.config.ts`.

**Comment by sebaguse** [comment]
Hi, thank you for your comments. I have SASS 1.62.1 installed and my `sassVariables` was set to `@/assets/quasar.variables.scss`. I tried `true` value, but there's no difference, I still get the same error.

**Comment by Maiquu** [comment]
Fixed with ([657056](https://github.com/Maiquu/nuxt-quasar/commit/657056))
