### ISSUE TITLE
[BUG] - Sass variable overrides lost when project is built for production

### ISSUE THREAD

**Issue by jfern01** [Maiquu/nuxt-quasar#67]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.20.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  npm@8.19.4
- Builder:          vite
- User Config:      extends, modules, hooks, app, css, nitro, routeRules, quasar, googleFonts, ogImage, schemaOrg, delayHydration, runtimeConfig, vite
- Runtime Modules:  nuxt-quasar-ui@2.0.2, nuxt-delay-hydration@1.2.1, nuxt-api-party@0.13.0, @pinia/nuxt@0.4.11, @nuxtjs/google-fonts@3.0.1, @nuxtjs/strapi@1.9.3
- Build Modules:    -
------------------------------

### Quasar version

2.12.2

### Browsers

Google Chrome, Firefox, Brave, Vivaldi, Ungoogled Chromium, Chromium, Opera, Safari, Microsoft Edge, Other

### Description

The sassVariables config works fine in development mode. As soon as the project is built for production, all the overrides are lost and all the default variables are used instead.

### Reproduction steps

```bash
1. Follow the steps in issue #6: https://github.com/Maiquu/nuxt-quasar/issues/6
2. npm run dev will show overridden variables
3. npm run build + npm run preview will revert everything back to default
```

**Comment by Maiquu** [comment]
Can you check latest version (2.0.3) and tell if the issue still persists?

**Comment by Maiquu** [comment]
You shouldn't need to do that step related to extending `vite.css.preprocessorOptions`

**Comment by jfern01** [comment]
Pulled in version 2.0.3, removed that config node and redeployed. It all works now. Thank you so much for jumping on this and for working on this much needed module.
