### ISSUE TITLE
[BUG] - RTL impact the entire styles not just quasar

### ISSUE THREAD

**Issue by spaceworkplatform** [Maiquu/nuxt-quasar#72]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  bun@1.0.0
- Builder:          -
- User Config:      experimental, app, devtools, postcss, quasar, imports, pinia, vuetify, googleFonts, modules
- Runtime Modules:  nuxt-lodash@2.5.0, @vueuse/nuxt@10.4.1, @pinia/nuxt@0.4.11, @nuxtjs/google-fonts@3.0.2, @nuxt/ui@2.8.1, @invictus.codes/nuxt-vuetify@0.3.0, nuxt-quasar-ui@2.0.5
- Build Modules:    -

### Quasar version

latest

### Browsers

Google Chrome

### Description

Hey,

First of all , great module !
Now, Im trying to migrate from quasar to Nuxt and on my quasar project I use RTL.

I found another issue that said to configure in nuxt.config.ts the following for RTL:
`
postcss: {
		plugins: {
		  'postcss-rtlcss': {
		  },
		},
	},
`

I did it, and its works, **problem is it also flip the entire css processed by nuxt and not only effect Quasar components styles**.

**Any suggestions how to get rtl working but just for quasar and not effect other css ?**

Thanks

### Reproduction steps

```bash
1. Install quasar module on nuxt project
2. Setup postcss on nuxt.config.ts
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Maiquu** [comment]
You can use [rtl ignore blocks](https://github.com/elchininet/postcss-rtlcss#rtlbeginignore-and-rtlendignore) to achieve that for specific sections of css you want `postcss-rtlcss` to ignore. If you want to ignore all except quasar css, you can do something like this.

### Basebones example
```ts

// How vite check if a file is css
// Source: https://github.com/vitejs/vite/blob/22bd67d70a1390daae19ca33d7de162140d533d6/packages/vite/src/node/plugins/css.ts#L188
const CSS_LANGS_RE =
/\.(css|less|sass|scss|styl|stylus|pcss|postcss|sss)(?:$|\?)/

const isCSSRequest = (request: string): boolean =>
  CSS_LANGS_RE.test(request)

export default defineNuxtConfig({
  // ...
  vite: {
    plugins: [
      {
        name: 'custom:css',
        enforce: 'pre',
        transform(code, id) {
          // If you are using `sassVariables`, you might need to update it with  'quasar/src/css/index.sass'
          // You can modify this section according to your needs
          if (isCSSRequest(id) && !id.endsWith('quasar/dist/quasar.css')) {
            return `/*rtl:begin:ignore*/\n${code}\n/*rtl:end:ignore*/`
          }
        }
      }
    ]
  }
  // ...
})
```

**Comment by spaceworkplatform** [comment]
@Maiquu Works like magic ! I was wondering how to configure something like that exactly, thank you :-)
