### ISSUE TITLE
💡 [REQUEST] - Fix Stackblitz demo

### ISSUE THREAD

**Issue by RemiMyrset** [Maiquu/nuxt-quasar#76]
In the [quasar module page](https://nuxt.com/modules/quasar) on nuxt there is a link to a demo on [Stackblitz](https://stackblitz.com/edit/github-g9bzsz?file=nuxt.config.ts)

After letting the demo start and run for one second, it will error out:
```
500
The requested module '/_nuxt/__quasar/entry.mjs' does not provide an export named 'QBtnProps'
```

**Comment by Maiquu** [comment]
Fixed
