### ISSUE TITLE
💡 [REQUEST] - Quasar App Extension Support?

### ISSUE THREAD

**Issue by TheCutter** [Maiquu/nuxt-quasar#77]
### Describe the feature

Is it possible to add Quasar Extensions with this module?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by Maiquu** [comment]
[Quasar Extensions](https://quasar.dev/app-extensions/introduction) are a feature of `@quasar/cli` which has its own set of rules. There are quite a lot of stuff an extension can do as listed in documents, so I do not think it is possible (or reasonable) to replicate it in nuxt environment.
