### ISSUE TITLE
[BUG] [DOCUMENTATION] - Markdown Syntax Error in README.md

### ISSUE THREAD

**Issue by jarp0l** [Maiquu/nuxt-quasar#78]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

n/a

### Quasar version

n/a

### Browsers

Other

### Description

I noticed a Markdown syntax error in the README.md file [on line 74](https://github.com/Maiquu/nuxt-quasar/blob/main/README.md?plain=1#L74). The issue is with the formatting of the link. The original line is:

```markdown
List of [quasar plugins]((https://github.com/Maiquu/nuxt-quasar/blob/main/src/types.ts#L6-L18)[]`) to apply.
```

The corrected version should be:

```markdown
List of [quasar plugins](https://github.com/Maiquu/nuxt-quasar/blob/main/src/types.ts#L6-L18) to apply.
```

This causes a broken link in https://nuxt.com/modules/quasar#plugins:
```md
https://github.com/Maiquu/nuxt-quasar/blob/main/(https://github.com/Maiquu/nuxt-quasar/blob/main/src/types.ts#L6-L18)[]`
```

### Reproduction steps

```bash
1. Go to https://nuxt.com/modules/quasar#plugins.
2. Click on "quasar plugins" link.
3. See 404 error.
```

**Comment by Maiquu** [comment]
Thanks! I had to remove the link completely due to the fact that source code no longer lists the plugins. Instead I put a few examples for context.
