### ISSUE TITLE
[BUG] - Error Component <Anonymous> is missing template or render function.

### ISSUE THREAD

**Issue by prashantnirgun** [Maiquu/nuxt-quasar#79]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

- Operating System: Linux
- Node Version:     v18.18.2
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, runtimeConfig, modules, quasar
- Runtime Modules:  nuxt-quasar-ui@2.0.6, @pinia/nuxt@0.5.1, @vee-validate/nuxt@4.11.8
- Build Modules:    -

### Quasar version

v2.14.0

### Browsers

Google Chrome

### Description

yarn build is successful then after is use node .output/server/index.mjs
Listening on http://[::]:3000
New request: GET http://X.X.X.X:3000/
[Vue warn]: Component <Anonymous> is missing template or render function.

I recreated this but fails

### Reproduction steps

```bash
1. git clone https://github.com/prashantnirgun/nuxt-quasar-boilderplate.git
2. cd nuxt-quasar-boilderplate
3. yarn add
4. yarn build
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
[Vue warn]: Component <Anonymous> is missing template or render function.
```

**Comment by Maiquu** [comment]
`app.vue` file seems to be missing from the repository link you provided. It works fine when I included it before building the project. Though it is kinda odd for build to succeed.

**Comment by prashantnirgun** [comment]
Thanks @Maiquu  its works but in nuxt we delete the app.vue if we are creating pages. so I just blindly delete the file. Thanks the help comes at right time. I was really frustrated as start building a quasar project from scratch. Thanks for your valuable help.

My plan was run it on Apache server (shared hosting) but the api routes failed as http://bmps.supermandi.in/members here it hit the GET request to http://bmps.supermandi.in/api/members but it failed. I know its a wrong place to ask. I tried to create .htaccess file and redirect it through index.html but it still didn't work.

You can close this thread, or discuss this further.
