### ISSUE TITLE
Example required set default configuration for Notify plugin

### ISSUE THREAD

**Issue by prashantnirgun** [Maiquu/nuxt-quasar#80]
### Describe the feature

I want to set default configuration for Notify plugin. I tried following but didn't work in nuxt.config.ts some bootfile or nuxt plugin to set the default configuration.

```
 quasar: {
    plugins: [
      ["Notify", { position: "top-right", timeout: 2500 }],
    ],
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by Maiquu** [comment]
You can configure plugins via the `config` key. For example:
```ts
export default defineNuxtConfig({
  quasar: {
    plugins: ['Notify'],
    config: {
      notify: {
        position: 'top-right',
      }
    }
  }
})
```
