### ISSUE TITLE
quasar auto importing everything even not imported

### ISSUE THREAD

**Issue by xalteropsx** [Maiquu/nuxt-quasar#82]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     -
- CLI Version:      3.10.0
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Quasar version

v2.14.1

### Browsers

Google Chrome, Firefox, Brave, Chromium, Other

### Description

quasar auto import - importing everything even it doesnt been used inside template 

 line modules: ['nuxt-quasar-ui'], and it will auto import component

### Reproduction steps

```bash
https://stackblitz.com/edit/github-vkmdsn?file=app.vue
```

### Screenshots

![289443384-1f616b35-ad74-45ff-9577-fd041732d956](https://github.com/Maiquu/nuxt-quasar/assets/103671642/9c770513-0133-49eb-95ec-9b2da9b9160d)

**Comment by marco-quintella** [comment]
Current workaround is to remove the entry file. Doesn't make it necessary on my tests. Reduced around of 200 files download when app is initiating.

![image](https://github.com/Maiquu/nuxt-quasar/assets/8003445/4d260ec7-fac6-4b68-83c5-5443da1c910a)

**Comment by Maiquu** [comment]
With v2.1.0, I eased up a lot on the excessive network requests. Now it should only import dist files like it used to be in earlier versions.
