### ISSUE TITLE
💡 [REQUEST] - Is there anyway to obfuscate css class?

### ISSUE THREAD

**Issue by AIRGG** [Maiquu/nuxt-quasar#89]
### Describe the feature

Hi, I try to combine `nuxt-obfuscator` & `nuxt-quasar-ui` then I got problem the css class is not transformed from component like q-btn, but when type it directly it's working, I don't know how exactly nuxt-quasar-ui working. you can check detail discussion in here https://github.com/jd1378/nuxt-obfuscator/issues/4

when it build/generate process, the output is still function or component with parameter I guess, so is there anyway to obfuscate css class from generated component like q-btn?

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Does this feature have a potential to break existing features?

**Comment by Maiquu** [comment]
By default `nuxt-obfuscator` checks files with `['.html', '.vue', '.jsx', '.tsx']` extensions. Quasar defines components in `.js` files. After enabling it, it appears to be working partially. Some patterns don't seem to be recognized by the  `nuxt-obfuscator` module.

**Comment by AIRGG** [comment]
Yeah but `nuxt-obfuscator` here said, [defaultExtensions](https://github.com/jd1378/nuxt-obfuscator/tree/main?tab=readme-ov-file#quick-setup) is all. `['.html', '.vue', '.jsx', '.tsx', '.ts', '.js']`
The main problem and some interesting is in [here](https://github.com/jd1378/nuxt-obfuscator/issues/4#issuecomment-1977953945), when doing build, it will be generated like [this](https://github.com/jd1378/nuxt-obfuscator/issues/4#issuecomment-1977973611) as you can see the different, if I type it manually and generated by component q-btn

Maybe you can help me to give me information, what the output generated q-btn mean after nuxt build process? I didn't see any of component q-btn in your repo, maybe I find it in wrong place

**Comment by Maiquu** [comment]
You should be the checking the [quasar](https://github.com/quasarframework/quasar) repository regarding components.

There are runtime generated classes in `QBtn` [source](https://github.com/quasarframework/quasar/blob/a64d3847a1566351ff8e43fecdfebbcc73faa94a/ui/src/components/btn/use-btn.js#L198-L207) which might be interfering with what you are trying to achieve.

**Comment by Maiquu** [comment]
Sorry, I don't think it is possible to completely obfuscate classes used in quasar.

> Yeah but nuxt-obfuscator here said, [defaultExtensions](https://github.com/jd1378/nuxt-obfuscator/tree/main?tab=readme-ov-file#quick-setup) is all. ['.html', '.vue', '.jsx', '.tsx', '.ts', '.js']

Think readme in that repo is outdated because in source its defined like [this](https://github.com/jd1378/nuxt-obfuscator/blob/12c1688241f8f069f3f326bdf1fddfd446e73116/src/module.ts#L30). You can still somewhat obfuscate though.

I'm closing this issue because it is out of scope of this module.
