### ISSUE TITLE
[BUG] - when npm install, it throws version driven error

### ISSUE THREAD

**Issue by Arnold-Youn** [Maiquu/nuxt-quasar#92]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v21.6.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Quasar version

v2.4.0

### Browsers

Google Chrome

### Description

when clone repo and run 'npm install'
Error occured.
below is detail of error
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nuxt-quasar-ui@2.0.8
npm ERR! Found: vitest@0.31.4
npm ERR! node_modules/vitest
npm ERR!   dev vitest@"^0.31.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional vitest@"^0.34.6 || ^1.0.0" from @nuxt/test-utils@3.12.0
npm ERR! node_modules/@nuxt/test-utils
npm ERR!   dev @nuxt/test-utils@"^3.12.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I've solved this issue with 'npm install --legacy-peer-deps'.
So, if you have same issue and it works, please correct your README.md

thank you. 

### Reproduction steps

```bash
1. clone repository
2. npm install
3. see error
```

**Comment by Maiquu** [comment]
If you want to contribute, you should be using `pnpm` as a package manager.
