### ISSUE TITLE
[BUG] - Quasar 2.16.0 break this module

### ISSUE THREAD

**Issue by Dodobibi** [Maiquu/nuxt-quasar#95]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.11.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.0.6
- Builder:          -
- User Config:      appConfig, modules, eslint, fonts, monaco, pwa, quasar, react, security, runtimeConfig, ssr, srcDir, routeRules, app, experimental, typescript, css, components, imports, devtools, nitro, vite
- Runtime Modules:  nuxt-quasar-ui@2.1.1, nuxt-security@2.0.0-beta.0, nuxt-lodash@2.5.3, @unocss/nuxt@0.59.4, @formkit/auto-animate/nuxt@0.8.2, @vueuse/nuxt@10.9.0, @pinia/nuxt@0.5.1, @nuxt/devtools@1.2.0, @vite-pwa/nuxt@0.7.0, @nuxt/fonts@0.7.0, @nuxt/eslint@0.3.10
- Build Modules:    -
------------------------------

### Quasar version

v2.16.0

### Browsers

Microsoft Edge

### Description

Since v2.16.0 : Quasar has converted “quasar” package internal build system to ESM (built dist/*.js are now renamed).
[Quasar release notes](https://quasar.dev/start/release-notes)

All quasar import must be adjusted for respect this behavior.

### Reproduction steps

```bash
1. Update quasar@2.16.0
2. run nuxi dev...
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
ERROR  Pre-transform error: Failed to resolve import "quasar/lang/fr.mjs" from ".nuxt/quasar.config.mjs". Does the file exist?

[7:52:59 PM]  ERROR  Pre-transform error: Failed to load url node_modules/quasar/dist/quasar.esm.js. Does the file exist?


[7:52:59 PM]  ERROR  Pre-transform error: Failed to load url node_modules/quasar/dist/quasar.esm.js. Does the file exist? (x2)
...
...
```

**Comment by Maiquu** [comment]
Fixed with `v.2.1.2`
