### ISSUE TITLE
💡 [REQUEST] - Allow to have multiple icon sets specified

### ISSUE THREAD

**Issue by Xkonti** [Maiquu/nuxt-quasar#97]
### Describe the feature

When using Quasar Framework via Quasar CLI, it's possible to have multiple icon sets at the same time. It would be helpful to have the same option in Nuxt.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by Maiquu** [comment]
Its possible to import mulltiple icon sets via `extras.fontIcons` at `nuxt.config.ts`.

```ts
export default defineNuxtConfig({
  quasar: {
    extras: {
      fontIcons: [
        // Enter any number of icon set collections you want that comes with `@quasar/extras`
      ]
    }
  }
}
```

Unless you mean something else, can you provide an example of what you mean.

**Comment by Xkonti** [comment]
It works! Now I have a config like this:

```js
quasar: {
  plugins: ["Dialog", "Loading", "LoadingBar", "Notify", "Dark"],
  extras: {
    font: "roboto-font",
    fontIcons: ["mdi-v7"],
  },
},
```

With this setup I can use both `material-icons` (enabled by default via `iconSet`) and `mdi-v7` set explicitly in `extras.fontIcons`. What's the difference between `extras.fontIcons` vs `iconSet` then?

**Comment by Maiquu** [comment]
`iconSet` is the icon set used by quasar components. (Like `QEditor`, `QDate`, `QColorPicker`)

`extras.fontIcons` simply imports font icon sets so you can use them with `QIcon` or any of the components with a `icon` prop.

**Comment by Xkonti** [comment]
Thanks @Maiquu . This makes it clear :)
